# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/serverless/apigateway/v1/apigateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6yandex/cloud/serverless/apigateway/v1/apigateway.proto\x12%yandex.cloud.serverless.apigateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x04\n\nApiGateway\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfolder_id\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12M\n\x06labels\x18\x07 \x03(\x0b\x32=.yandex.cloud.serverless.apigateway.v1.ApiGateway.LabelsEntry\x12H\n\x06status\x18\x08 \x01(\x0e\x32\x38.yandex.cloud.serverless.apigateway.v1.ApiGateway.Status\x12\x0e\n\x06\x64omain\x18\t \x01(\t\x12\x14\n\x0clog_group_id\x18\n \x01(\t\x12O\n\x10\x61ttached_domains\x18\x0b \x03(\x0b\x32\x35.yandex.cloud.serverless.apigateway.v1.AttachedDomain\x12I\n\x0c\x63onnectivity\x18\x0c \x01(\x0b\x32\x33.yandex.cloud.serverless.apigateway.v1.Connectivity\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"a\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0c\n\x08\x43REATING\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x12\x0c\n\x08\x44\x45LETING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0c\n\x08UPDATING\x10\x05\"\\\n\x0e\x41ttachedDomain\x12\x11\n\tdomain_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x65rtificate_id\x18\x02 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x12\x0e\n\x06\x64omain\x18\x05 \x01(\t\"5\n\x0c\x43onnectivity\x12\x12\n\nnetwork_id\x18\x01 \x01(\t\x12\x11\n\tsubnet_id\x18\x02 \x03(\tB\x81\x01\n)yandex.cloud.api.serverless.apigateway.v1ZTgithub.com/yandex-cloud/go-genproto/yandex/cloud/serverless/apigateway/v1;apigatewayb\x06proto3')



_APIGATEWAY = DESCRIPTOR.message_types_by_name['ApiGateway']
_APIGATEWAY_LABELSENTRY = _APIGATEWAY.nested_types_by_name['LabelsEntry']
_ATTACHEDDOMAIN = DESCRIPTOR.message_types_by_name['AttachedDomain']
_CONNECTIVITY = DESCRIPTOR.message_types_by_name['Connectivity']
_APIGATEWAY_STATUS = _APIGATEWAY.enum_types_by_name['Status']
ApiGateway = _reflection.GeneratedProtocolMessageType('ApiGateway', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _APIGATEWAY_LABELSENTRY,
    '__module__' : 'yandex.cloud.serverless.apigateway.v1.apigateway_pb2'
    # @@protoc_insertion_point(class_scope:yandex.cloud.serverless.apigateway.v1.ApiGateway.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : _APIGATEWAY,
  '__module__' : 'yandex.cloud.serverless.apigateway.v1.apigateway_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.serverless.apigateway.v1.ApiGateway)
  })
_sym_db.RegisterMessage(ApiGateway)
_sym_db.RegisterMessage(ApiGateway.LabelsEntry)

AttachedDomain = _reflection.GeneratedProtocolMessageType('AttachedDomain', (_message.Message,), {
  'DESCRIPTOR' : _ATTACHEDDOMAIN,
  '__module__' : 'yandex.cloud.serverless.apigateway.v1.apigateway_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.serverless.apigateway.v1.AttachedDomain)
  })
_sym_db.RegisterMessage(AttachedDomain)

Connectivity = _reflection.GeneratedProtocolMessageType('Connectivity', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIVITY,
  '__module__' : 'yandex.cloud.serverless.apigateway.v1.apigateway_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.serverless.apigateway.v1.Connectivity)
  })
_sym_db.RegisterMessage(Connectivity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)yandex.cloud.api.serverless.apigateway.v1ZTgithub.com/yandex-cloud/go-genproto/yandex/cloud/serverless/apigateway/v1;apigateway'
  _APIGATEWAY_LABELSENTRY._options = None
  _APIGATEWAY_LABELSENTRY._serialized_options = b'8\001'
  _APIGATEWAY._serialized_start=131
  _APIGATEWAY._serialized_end=750
  _APIGATEWAY_LABELSENTRY._serialized_start=606
  _APIGATEWAY_LABELSENTRY._serialized_end=651
  _APIGATEWAY_STATUS._serialized_start=653
  _APIGATEWAY_STATUS._serialized_end=750
  _ATTACHEDDOMAIN._serialized_start=752
  _ATTACHEDDOMAIN._serialized_end=844
  _CONNECTIVITY._serialized_start=846
  _CONNECTIVITY._serialized_end=899
# @@protoc_insertion_point(module_scope)
