# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/vision/v1/image_copy_search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1yandex/cloud/ai/vision/v1/image_copy_search.proto\x12\x19yandex.cloud.ai.vision.v1\"j\n\x19ImageCopySearchAnnotation\x12\x12\n\ncopy_count\x18\x01 \x01(\x03\x12\x39\n\x0btop_results\x18\x02 \x03(\x0b\x32$.yandex.cloud.ai.vision.v1.CopyMatch\"T\n\tCopyMatch\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x10\n\x08page_url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\tBe\n\x1dyandex.cloud.api.ai.vision.v1ZDgithub.com/yandex-cloud/go-genproto/yandex/cloud/ai/vision/v1;visionb\x06proto3')



_IMAGECOPYSEARCHANNOTATION = DESCRIPTOR.message_types_by_name['ImageCopySearchAnnotation']
_COPYMATCH = DESCRIPTOR.message_types_by_name['CopyMatch']
ImageCopySearchAnnotation = _reflection.GeneratedProtocolMessageType('ImageCopySearchAnnotation', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECOPYSEARCHANNOTATION,
  '__module__' : 'yandex.cloud.ai.vision.v1.image_copy_search_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.ImageCopySearchAnnotation)
  })
_sym_db.RegisterMessage(ImageCopySearchAnnotation)

CopyMatch = _reflection.GeneratedProtocolMessageType('CopyMatch', (_message.Message,), {
  'DESCRIPTOR' : _COPYMATCH,
  '__module__' : 'yandex.cloud.ai.vision.v1.image_copy_search_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.CopyMatch)
  })
_sym_db.RegisterMessage(CopyMatch)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035yandex.cloud.api.ai.vision.v1ZDgithub.com/yandex-cloud/go-genproto/yandex/cloud/ai/vision/v1;vision'
  _IMAGECOPYSEARCHANNOTATION._serialized_start=80
  _IMAGECOPYSEARCHANNOTATION._serialized_end=186
  _COPYMATCH._serialized_start=188
  _COPYMATCH._serialized_end=272
# @@protoc_insertion_point(module_scope)
