# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/vision/v1/text_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yandex.cloud.ai.vision.v1 import primitives_pb2 as yandex_dot_cloud_dot_ai_dot_vision_dot_v1_dot_primitives__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.yandex/cloud/ai/vision/v1/text_detection.proto\x12\x19yandex.cloud.ai.vision.v1\x1a*yandex/cloud/ai/vision/v1/primitives.proto\"@\n\x0eTextAnnotation\x12.\n\x05pages\x18\x01 \x03(\x0b\x32\x1f.yandex.cloud.ai.vision.v1.Page\"\x8c\x01\n\x04Page\x12\r\n\x05width\x18\x01 \x01(\x03\x12\x0e\n\x06height\x18\x02 \x01(\x03\x12\x30\n\x06\x62locks\x18\x03 \x03(\x0b\x32 .yandex.cloud.ai.vision.v1.Block\x12\x33\n\x08\x65ntities\x18\x04 \x03(\x0b\x32!.yandex.cloud.ai.vision.v1.Entity\"$\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"q\n\x05\x42lock\x12\x38\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\".yandex.cloud.ai.vision.v1.Polygon\x12.\n\x05lines\x18\x02 \x03(\x0b\x32\x1f.yandex.cloud.ai.vision.v1.Line\"\x84\x01\n\x04Line\x12\x38\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\".yandex.cloud.ai.vision.v1.Polygon\x12.\n\x05words\x18\x02 \x03(\x0b\x32\x1f.yandex.cloud.ai.vision.v1.Word\x12\x12\n\nconfidence\x18\x03 \x01(\x01\"\xfc\x01\n\x04Word\x12\x38\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\".yandex.cloud.ai.vision.v1.Polygon\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x43\n\tlanguages\x18\x04 \x03(\x0b\x32\x30.yandex.cloud.ai.vision.v1.Word.DetectedLanguage\x12\x14\n\x0c\x65ntity_index\x18\x05 \x01(\x03\x1a=\n\x10\x44\x65tectedLanguage\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x42\x65\n\x1dyandex.cloud.api.ai.vision.v1ZDgithub.com/yandex-cloud/go-genproto/yandex/cloud/ai/vision/v1;visionb\x06proto3')



_TEXTANNOTATION = DESCRIPTOR.message_types_by_name['TextAnnotation']
_PAGE = DESCRIPTOR.message_types_by_name['Page']
_ENTITY = DESCRIPTOR.message_types_by_name['Entity']
_BLOCK = DESCRIPTOR.message_types_by_name['Block']
_LINE = DESCRIPTOR.message_types_by_name['Line']
_WORD = DESCRIPTOR.message_types_by_name['Word']
_WORD_DETECTEDLANGUAGE = _WORD.nested_types_by_name['DetectedLanguage']
TextAnnotation = _reflection.GeneratedProtocolMessageType('TextAnnotation', (_message.Message,), {
  'DESCRIPTOR' : _TEXTANNOTATION,
  '__module__' : 'yandex.cloud.ai.vision.v1.text_detection_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.TextAnnotation)
  })
_sym_db.RegisterMessage(TextAnnotation)

Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), {
  'DESCRIPTOR' : _PAGE,
  '__module__' : 'yandex.cloud.ai.vision.v1.text_detection_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.Page)
  })
_sym_db.RegisterMessage(Page)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'yandex.cloud.ai.vision.v1.text_detection_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.Entity)
  })
_sym_db.RegisterMessage(Entity)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'yandex.cloud.ai.vision.v1.text_detection_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.Block)
  })
_sym_db.RegisterMessage(Block)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), {
  'DESCRIPTOR' : _LINE,
  '__module__' : 'yandex.cloud.ai.vision.v1.text_detection_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.Line)
  })
_sym_db.RegisterMessage(Line)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {

  'DetectedLanguage' : _reflection.GeneratedProtocolMessageType('DetectedLanguage', (_message.Message,), {
    'DESCRIPTOR' : _WORD_DETECTEDLANGUAGE,
    '__module__' : 'yandex.cloud.ai.vision.v1.text_detection_pb2'
    # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.Word.DetectedLanguage)
    })
  ,
  'DESCRIPTOR' : _WORD,
  '__module__' : 'yandex.cloud.ai.vision.v1.text_detection_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.ai.vision.v1.Word)
  })
_sym_db.RegisterMessage(Word)
_sym_db.RegisterMessage(Word.DetectedLanguage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035yandex.cloud.api.ai.vision.v1ZDgithub.com/yandex-cloud/go-genproto/yandex/cloud/ai/vision/v1;vision'
  _TEXTANNOTATION._serialized_start=121
  _TEXTANNOTATION._serialized_end=185
  _PAGE._serialized_start=188
  _PAGE._serialized_end=328
  _ENTITY._serialized_start=330
  _ENTITY._serialized_end=366
  _BLOCK._serialized_start=368
  _BLOCK._serialized_end=481
  _LINE._serialized_start=484
  _LINE._serialized_end=616
  _WORD._serialized_start=619
  _WORD._serialized_end=871
  _WORD_DETECTEDLANGUAGE._serialized_start=810
  _WORD_DETECTEDLANGUAGE._serialized_end=871
# @@protoc_insertion_point(module_scope)
