# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/mdb/elasticsearch/v1/resource_preset_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from yandex.cloud.mdb.elasticsearch.v1 import resource_preset_pb2 as yandex_dot_cloud_dot_mdb_dot_elasticsearch_dot_v1_dot_resource__preset__pb2
from yandex.cloud import validation_pb2 as yandex_dot_cloud_dot_validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?yandex/cloud/mdb/elasticsearch/v1/resource_preset_service.proto\x12!yandex.cloud.mdb.elasticsearch.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x37yandex/cloud/mdb/elasticsearch/v1/resource_preset.proto\x1a\x1dyandex/cloud/validation.proto\"<\n\x18GetResourcePresetRequest\x12 \n\x12resource_preset_id\x18\x01 \x01(\tB\x04\xe8\xc7\x31\x01\"Z\n\x1aListResourcePresetsRequest\x12\x1d\n\tpage_size\x18\x01 \x01(\x03\x42\n\xfa\xc7\x31\x06<=1000\x12\x1d\n\npage_token\x18\x02 \x01(\tB\t\x8a\xc8\x31\x05<=100\"\x8e\x01\n\x1bListResourcePresetsResponse\x12K\n\x10resource_presets\x18\x01 \x03(\x0b\x32\x31.yandex.cloud.mdb.elasticsearch.v1.ResourcePreset\x12\"\n\x0fnext_page_token\x18\x02 \x01(\tB\t\x8a\xc8\x31\x05<=1002\x92\x03\n\x15ResourcePresetService\x12\xbd\x01\n\x03Get\x12;.yandex.cloud.mdb.elasticsearch.v1.GetResourcePresetRequest\x1a\x31.yandex.cloud.mdb.elasticsearch.v1.ResourcePreset\"F\x82\xd3\xe4\x93\x02@\x12>/managed-elasticsearch/v1/resourcePresets/{resource_preset_id}\x12\xb8\x01\n\x04List\x12=.yandex.cloud.mdb.elasticsearch.v1.ListResourcePresetsRequest\x1a>.yandex.cloud.mdb.elasticsearch.v1.ListResourcePresetsResponse\"1\x82\xd3\xe4\x93\x02+\x12)/managed-elasticsearch/v1/resourcePresetsB|\n%yandex.cloud.api.mdb.elasticsearch.v1ZSgithub.com/yandex-cloud/go-genproto/yandex/cloud/mdb/elasticsearch/v1;elasticsearchb\x06proto3')



_GETRESOURCEPRESETREQUEST = DESCRIPTOR.message_types_by_name['GetResourcePresetRequest']
_LISTRESOURCEPRESETSREQUEST = DESCRIPTOR.message_types_by_name['ListResourcePresetsRequest']
_LISTRESOURCEPRESETSRESPONSE = DESCRIPTOR.message_types_by_name['ListResourcePresetsResponse']
GetResourcePresetRequest = _reflection.GeneratedProtocolMessageType('GetResourcePresetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRESOURCEPRESETREQUEST,
  '__module__' : 'yandex.cloud.mdb.elasticsearch.v1.resource_preset_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.mdb.elasticsearch.v1.GetResourcePresetRequest)
  })
_sym_db.RegisterMessage(GetResourcePresetRequest)

ListResourcePresetsRequest = _reflection.GeneratedProtocolMessageType('ListResourcePresetsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESOURCEPRESETSREQUEST,
  '__module__' : 'yandex.cloud.mdb.elasticsearch.v1.resource_preset_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.mdb.elasticsearch.v1.ListResourcePresetsRequest)
  })
_sym_db.RegisterMessage(ListResourcePresetsRequest)

ListResourcePresetsResponse = _reflection.GeneratedProtocolMessageType('ListResourcePresetsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESOURCEPRESETSRESPONSE,
  '__module__' : 'yandex.cloud.mdb.elasticsearch.v1.resource_preset_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.mdb.elasticsearch.v1.ListResourcePresetsResponse)
  })
_sym_db.RegisterMessage(ListResourcePresetsResponse)

_RESOURCEPRESETSERVICE = DESCRIPTOR.services_by_name['ResourcePresetService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%yandex.cloud.api.mdb.elasticsearch.v1ZSgithub.com/yandex-cloud/go-genproto/yandex/cloud/mdb/elasticsearch/v1;elasticsearch'
  _GETRESOURCEPRESETREQUEST.fields_by_name['resource_preset_id']._options = None
  _GETRESOURCEPRESETREQUEST.fields_by_name['resource_preset_id']._serialized_options = b'\350\3071\001'
  _LISTRESOURCEPRESETSREQUEST.fields_by_name['page_size']._options = None
  _LISTRESOURCEPRESETSREQUEST.fields_by_name['page_size']._serialized_options = b'\372\3071\006<=1000'
  _LISTRESOURCEPRESETSREQUEST.fields_by_name['page_token']._options = None
  _LISTRESOURCEPRESETSREQUEST.fields_by_name['page_token']._serialized_options = b'\212\3101\005<=100'
  _LISTRESOURCEPRESETSRESPONSE.fields_by_name['next_page_token']._options = None
  _LISTRESOURCEPRESETSRESPONSE.fields_by_name['next_page_token']._serialized_options = b'\212\3101\005<=100'
  _RESOURCEPRESETSERVICE.methods_by_name['Get']._options = None
  _RESOURCEPRESETSERVICE.methods_by_name['Get']._serialized_options = b'\202\323\344\223\002@\022>/managed-elasticsearch/v1/resourcePresets/{resource_preset_id}'
  _RESOURCEPRESETSERVICE.methods_by_name['List']._options = None
  _RESOURCEPRESETSERVICE.methods_by_name['List']._serialized_options = b'\202\323\344\223\002+\022)/managed-elasticsearch/v1/resourcePresets'
  _GETRESOURCEPRESETREQUEST._serialized_start=220
  _GETRESOURCEPRESETREQUEST._serialized_end=280
  _LISTRESOURCEPRESETSREQUEST._serialized_start=282
  _LISTRESOURCEPRESETSREQUEST._serialized_end=372
  _LISTRESOURCEPRESETSRESPONSE._serialized_start=375
  _LISTRESOURCEPRESETSRESPONSE._serialized_end=517
  _RESOURCEPRESETSERVICE._serialized_start=520
  _RESOURCEPRESETSERVICE._serialized_end=922
# @@protoc_insertion_point(module_scope)
