name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    # disallows two or more release jobs to run in parallel
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      run: |
        make release
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        repository_username: __token__
#        repository_password: ${{ secrets.PYPI_TOKEN }}
